[project]
name = "aoc-2024"
version = "0.1.0"
description = "Advent of Code 2024"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "advent-of-code-data>=2.0.4",
    "mypy>=1.13.0",
    "pudb>=2024.1.3",
    "ruff>=0.8.1",
]
